name: Compilar y desplegar

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/compilar-desplegar.yml'
      - 'GithubActionsDemoApp/**'
      - 'Pruebas/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 8.0.x

    - name: Obteniendo dependencias
      run: dotnet restore

    - name: Compilar
      run: dotnet build --no-restore

    - name: Test y validaciones
      run: dotnet test --no-build

    - name: dotnet publish
      run: dotnet publish $proyecto -c Release -o miapp --runtime win-x86

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        path: ./miapp
        name: build

